// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.51
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace OsipDal.EF
{

    // Answer
    [System.CodeDom.Compiler.GeneratedCodeAttribute("EF.Reverse.POCO.Generator", "2.19.1.0")]
    public class AnswerConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<Answer>
    {
        public AnswerConfiguration()
            : this("dbo")
        {
        }
 
        public AnswerConfiguration(string schema)
        {
            ToTable(schema + ".Answer");
            HasKey(x => x.Id);

            Property(x => x.Id).HasColumnName("ID").IsRequired().HasColumnType("int").HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None);
            Property(x => x.AnswerAsString).HasColumnName("AnswerAsString").IsRequired().IsUnicode(false).HasColumnType("varchar");
            Property(x => x.QuestionId).HasColumnName("QuestionID").IsRequired().HasColumnType("int");

            // Foreign keys
            HasRequired(a => a.Question).WithMany(b => b.Answers).HasForeignKey(c => c.QuestionId); // FK_Answer_Question
            HasMany(t => t.QuestionRanges).WithMany(t => t.Answers).Map(m => 
            {
                m.ToTable("AnswerRangeGroup", "dbo");
                m.MapLeftKey("AnswerID");
                m.MapRightKey("QuestionRangeID");
            });
            HasMany(t => t.Policies).WithMany(t => t.Answers).Map(m => 
            {
                m.ToTable("PolicyAnswer", "dbo");
                m.MapLeftKey("AnswerID");
                m.MapRightKey("PolicyID");
            });
        }
    }

}
// </auto-generated>
