// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.51
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace OsipDal.EF
{

    // Country
    [System.CodeDom.Compiler.GeneratedCodeAttribute("EF.Reverse.POCO.Generator", "2.19.1.0")]
    public class Country
    {
        public int Id { get; set; } // ID (Primary key)
        public string CountryName { get; set; } // CountryName (length: 20)
        public string CountryCode { get; set; } // CountryCode (length: 3)

        // Reverse navigation
        public virtual System.Collections.Generic.ICollection<Address> Addresses { get; set; } // Address.FK_Address_Country
        public virtual System.Collections.Generic.ICollection<CountryInRegion> CountryInRegions { get; set; } // Many to many mapping
        public virtual System.Collections.Generic.ICollection<Town> Towns { get; set; } // Many to many mapping
        
        public Country()
        {
            Addresses = new System.Collections.Generic.List<Address>();
            CountryInRegions = new System.Collections.Generic.List<CountryInRegion>();
            Towns = new System.Collections.Generic.List<Town>();
        }
    }

}
// </auto-generated>
