// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.51
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace OsipDal.EF
{

    // GlobalRegionSet
    [System.CodeDom.Compiler.GeneratedCodeAttribute("EF.Reverse.POCO.Generator", "2.19.1.0")]
    public class GlobalRegionSetConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<GlobalRegionSet>
    {
        public GlobalRegionSetConfiguration()
            : this("dbo")
        {
        }
 
        public GlobalRegionSetConfiguration(string schema)
        {
            ToTable(schema + ".GlobalRegionSet");
            HasKey(x => x.Id);

            Property(x => x.Id).HasColumnName("ID").IsRequired().HasColumnType("int").HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None);
            Property(x => x.RegionSetName).HasColumnName("RegionSetName").IsRequired().IsFixedLength().HasColumnType("nchar").HasMaxLength(10);
        }
    }

}
// </auto-generated>
