// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.51
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace OsipDal.EF
{

    // PersonLogin
    [System.CodeDom.Compiler.GeneratedCodeAttribute("EF.Reverse.POCO.Generator", "2.19.1.0")]
    public class PersonLoginConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<PersonLogin>
    {
        public PersonLoginConfiguration()
            : this("dbo")
        {
        }
 
        public PersonLoginConfiguration(string schema)
        {
            ToTable(schema + ".PersonLogin");
            HasKey(x => new { x.PersonId, x.LoginId, x.TargetSystemId });

            Property(x => x.PersonId).HasColumnName("PersonID").IsRequired().HasColumnType("int").HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None);
            Property(x => x.LoginId).HasColumnName("LoginID").IsRequired().HasColumnType("int").HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None);
            Property(x => x.TargetSystemId).HasColumnName("targetSystemID").IsRequired().HasColumnType("int").HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None);

            // Foreign keys
            HasRequired(a => a.Login).WithMany(b => b.PersonLogins).HasForeignKey(c => c.LoginId); // FK_PersonLogin_Login
            HasRequired(a => a.Person).WithMany(b => b.PersonLogins).HasForeignKey(c => c.PersonId); // FK_PersonLogin_Person
            HasRequired(a => a.TargetSystem).WithMany(b => b.PersonLogins).HasForeignKey(c => c.TargetSystemId); // FK_PersonLogin_TargetSystem
        }
    }

}
// </auto-generated>
