// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.51
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace OsipDal.EF
{

    // Policy
    [System.CodeDom.Compiler.GeneratedCodeAttribute("EF.Reverse.POCO.Generator", "2.19.1.0")]
    public class Policy
    {
        public int Id { get; set; } // ID (Primary key)
        public int PurchaserId { get; set; } // PurchaserID
        public System.DateTime StartDate { get; set; } // StartDate
        public int? DurationInDays { get; set; } // DurationInDays
        public System.DateTime QuoteDate { get; set; } // QuoteDate
        public int PolicyDefinitionId { get; set; } // PolicyDefinitionID
        public decimal Premium { get; set; } // Premium
        public bool PolicyAutoRenew { get; set; } // PolicyAutoRenew
        public int SoldById { get; set; } // SoldByID

        ///<summary>
        /// 0 all docs and written comms via email - 1 using physical post
        ///</summary>
        public bool SnailMail { get; set; } // SnailMail

        // Reverse navigation
        public virtual System.Collections.Generic.ICollection<AddOn> AddOns { get; set; } // Many to many mapping
        public virtual System.Collections.Generic.ICollection<Address> Addresses { get; set; } // Many to many mapping
        public virtual System.Collections.Generic.ICollection<Answer> Answers { get; set; } // Many to many mapping
        public virtual System.Collections.Generic.ICollection<Person> People { get; set; } // Many to many mapping
        public virtual System.Collections.Generic.ICollection<PolicyAmendment> PolicyAmendments { get; set; } // PolicyAmendment.FK_PolicyAmendment_Policy
        public virtual System.Collections.Generic.ICollection<RatingFactorOnPolicy> RatingFactorOnPolicies { get; set; } // Many to many mapping

        // Foreign keys
        public virtual PolicyDefinition PolicyDefinition { get; set; } // FK_Policy_PolicyDefinition
        
        public Policy()
        {
            PolicyAutoRenew = true;
            SnailMail = false;
            PolicyAmendments = new System.Collections.Generic.List<PolicyAmendment>();
            RatingFactorOnPolicies = new System.Collections.Generic.List<RatingFactorOnPolicy>();
            People = new System.Collections.Generic.List<Person>();
            Addresses = new System.Collections.Generic.List<Address>();
            AddOns = new System.Collections.Generic.List<AddOn>();
            Answers = new System.Collections.Generic.List<Answer>();
        }
    }

}
// </auto-generated>
