// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.51
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace OsipDal.EF
{

    // PolicyDefinition
    [System.CodeDom.Compiler.GeneratedCodeAttribute("EF.Reverse.POCO.Generator", "2.19.1.0")]
    public class PolicyDefinitionConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<PolicyDefinition>
    {
        public PolicyDefinitionConfiguration()
            : this("dbo")
        {
        }
 
        public PolicyDefinitionConfiguration(string schema)
        {
            ToTable(schema + ".PolicyDefinition");
            HasKey(x => x.Id);

            Property(x => x.Id).HasColumnName("ID").IsRequired().HasColumnType("int").HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None);
            Property(x => x.PolicyTypeId).HasColumnName("PolicyTypeID").IsRequired().HasColumnType("int");
            Property(x => x.DefinitionName).HasColumnName("DefinitionName").IsRequired().IsUnicode(false).HasColumnType("varchar").HasMaxLength(30);
            Property(x => x.ProvidorOrUnderWriterId).HasColumnName("ProvidorOrUnderWriterID").IsOptional().HasColumnType("int");

            // Foreign keys
            HasOptional(a => a.Provider).WithMany(b => b.PolicyDefinitions).HasForeignKey(c => c.ProvidorOrUnderWriterId); // FK_PolicyDefinition_Provider
            HasRequired(a => a.PolicyType).WithMany(b => b.PolicyDefinitions).HasForeignKey(c => c.PolicyTypeId); // FK_PolicyDefinition_PolicyType
            HasMany(t => t.Questions).WithMany(t => t.PolicyDefinitions).Map(m => 
            {
                m.ToTable("PolicyQuestion", "dbo");
                m.MapLeftKey("PolicyDefinitionID");
                m.MapRightKey("QuestionID");
            });
        }
    }

}
// </auto-generated>
