// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.51
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace OsipDal.EF
{

    // QuestionMultipleChoiceGroup
    [System.CodeDom.Compiler.GeneratedCodeAttribute("EF.Reverse.POCO.Generator", "2.19.1.0")]
    public class QuestionMultipleChoiceGroupConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<QuestionMultipleChoiceGroup>
    {
        public QuestionMultipleChoiceGroupConfiguration()
            : this("dbo")
        {
        }
 
        public QuestionMultipleChoiceGroupConfiguration(string schema)
        {
            ToTable(schema + ".QuestionMultipleChoiceGroup");
            HasKey(x => new { x.QuestionId, x.QuestionMultipleChoiceId });

            Property(x => x.QuestionId).HasColumnName("QuestionID").IsRequired().HasColumnType("int").HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None);
            Property(x => x.QuestionMultipleChoiceId).HasColumnName("QuestionMultipleChoiceID").IsRequired().HasColumnType("int").HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None);

            // Foreign keys
            HasRequired(a => a.Question).WithMany(b => b.QuestionMultipleChoiceGroups).HasForeignKey(c => c.QuestionId); // FK_QuestionMultipleChoiceGroup_Question
            HasRequired(a => a.QuestionMultiChoice).WithMany(b => b.QuestionMultipleChoiceGroups).HasForeignKey(c => c.QuestionId); // FK_QuestionMultipleChoiceGroup_QuestionMultiChoice
        }
    }

}
// </auto-generated>
