// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.51
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace OsipDal.EF
{

    // QuestionMultipleChoiceGroup
    [System.CodeDom.Compiler.GeneratedCodeAttribute("EF.Reverse.POCO.Generator", "2.19.1.0")]
    public class QuestionMultipleChoiceGroup
    {
        public int QuestionId { get; set; } // QuestionID (Primary key)
        public int QuestionMultipleChoiceId { get; set; } // QuestionMultipleChoiceID (Primary key)

        // Foreign keys
        public virtual Question Question { get; set; } // FK_QuestionMultipleChoiceGroup_Question
        public virtual QuestionMultiChoice QuestionMultiChoice { get; set; } // FK_QuestionMultipleChoiceGroup_QuestionMultiChoice
    }

}
// </auto-generated>
