// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.51
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace OsipDal.EF
{

    // QuestionMultiChoice
    [System.CodeDom.Compiler.GeneratedCodeAttribute("EF.Reverse.POCO.Generator", "2.19.1.0")]
    public class QuestionMultiChoice
    {
        public int Id { get; set; } // ID (Primary key)
        public string Choice { get; set; } // Choice (length: 50)

        // Reverse navigation
        public virtual System.Collections.Generic.ICollection<QuestionMultipleChoiceGroup> QuestionMultipleChoiceGroups { get; set; } // Many to many mapping
        
        public QuestionMultiChoice()
        {
            QuestionMultipleChoiceGroups = new System.Collections.Generic.List<QuestionMultipleChoiceGroup>();
        }
    }

}
// </auto-generated>
