// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.51
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace OsipDal.EF
{

    // RatingBaseRate
    [System.CodeDom.Compiler.GeneratedCodeAttribute("EF.Reverse.POCO.Generator", "2.19.1.0")]
    public class RatingBaseRate
    {
        public int Id { get; set; } // ID (Primary key)
        public int ProviderId { get; set; } // ProviderID
        public System.DateTime ValidFrom { get; set; } // ValidFrom
        public System.DateTime? ValidTo { get; set; } // ValidTo
        public decimal BaseRate { get; set; } // BaseRate

        // Reverse navigation
        public virtual System.Collections.Generic.ICollection<RatingFactor> RatingFactors { get; set; } // RatingFactor.FK_RatingFactor_RatingBaseRate
        
        public RatingBaseRate()
        {
            ValidFrom = System.DateTime.Now;
            RatingFactors = new System.Collections.Generic.List<RatingFactor>();
        }
    }

}
// </auto-generated>
