// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.51
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace OsipDal.EF
{

    // PersonEmailAddress
    [System.CodeDom.Compiler.GeneratedCodeAttribute("EF.Reverse.POCO.Generator", "2.19.1.0")]
    public class PersonEmailAddress
    {
        public int EmailAddressId { get; set; } // EmailAddressID (Primary key)
        public int PersonId { get; set; } // PersonID (Primary key)
        public int EmailAddressTypeId { get; set; } // EmailAddressTypeID (Primary key)

        // Foreign keys
        public virtual EmailAddress EmailAddress { get; set; } // FK_PersonEmailAddress_EmailAddress
        public virtual EmailAddressType EmailAddressType { get; set; } // FK_PersonEmailAddress_EmailAddressType
        public virtual Person Person { get; set; } // FK_PersonEmailAddress_Person
    }

}
// </auto-generated>
