// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.51
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace Pocos
{

    // AddressType
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.24.0.0")]
    public class AddressType
    {
        public int Id { get; set; } // ID (Primary key)
        public string AddressTypeName { get; set; } // AddressTypeName (length: 20)

        // Reverse navigation
        public virtual System.Collections.Generic.ICollection<PersonAddress> PersonAddresses { get; set; } // Many to many mapping

        public AddressType()
        {
            PersonAddresses = new System.Collections.Generic.List<PersonAddress>();
        }
    }

}
// </auto-generated>
