// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.51
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace Pocos
{

    // Answer
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.24.0.0")]
    public class Answer
    {
        public int Id { get; set; } // ID (Primary key)
        public string AnswerAsString { get; set; } // AnswerAsString
        public int QuestionId { get; set; } // QuestionID

        // Reverse navigation
        public virtual System.Collections.Generic.ICollection<Policy> Policies { get; set; } // Many to many mapping
        public virtual System.Collections.Generic.ICollection<QuestionRange> QuestionRanges { get; set; } // Many to many mapping
        public virtual System.Collections.Generic.ICollection<RatingFactorOnPolicy> RatingFactorOnPolicies { get; set; } // Many to many mapping

        // Foreign keys
        public virtual Question Question { get; set; } // FK_Answer_Question

        public Answer()
        {
            RatingFactorOnPolicies = new System.Collections.Generic.List<RatingFactorOnPolicy>();
            QuestionRanges = new System.Collections.Generic.List<QuestionRange>();
            Policies = new System.Collections.Generic.List<Policy>();
        }
    }

}
// </auto-generated>
