// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.51
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace Pocos
{

    // CountryInRegion
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.24.0.0")]
    public class CountryInRegion
    {
        public int GlobalRegionId { get; set; } // GlobalRegionID (Primary key)
        public int CountryId { get; set; } // CountryID (Primary key)
        public int RegionSetId { get; set; } // RegionSetID (Primary key)

        // Foreign keys
        public virtual Country Country { get; set; } // FK_CountryInRegion_Country
        public virtual GlobalRegion GlobalRegion { get; set; } // FK_CountryInRegion_GlobalRegion
        public virtual GlobalRegionSet GlobalRegionSet { get; set; } // FK_CountryInRegion_GlobalRegionSet
    }

}
// </auto-generated>
