// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.51
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace Pocos
{

    // Login
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.24.0.0")]
    public class Login
    {
        public int Id { get; set; } // ID (Primary key)
        public string Login_ { get; set; } // Login (length: 50)

        // Reverse navigation
        public virtual System.Collections.Generic.ICollection<PersonLogin> PersonLogins { get; set; } // Many to many mapping

        public Login()
        {
            PersonLogins = new System.Collections.Generic.List<PersonLogin>();
        }
    }

}
// </auto-generated>
