// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.51
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace Pocos
{

    // PersonPassword
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.24.0.0")]
    public class PersonPasswordConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<PersonPassword>
    {
        public PersonPasswordConfiguration()
            : this("dbo")
        {
        }

        public PersonPasswordConfiguration(string schema)
        {
            ToTable("PersonPassword", schema);
            HasKey(x => new { x.PersonId, x.PasswordId, x.TargetSystemId });

            Property(x => x.PersonId).HasColumnName(@"PersonID").IsRequired().HasColumnType("int").HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None);
            Property(x => x.PasswordId).HasColumnName(@"PasswordID").IsRequired().HasColumnType("int").HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None);
            Property(x => x.TargetSystemId).HasColumnName(@"TargetSystemID").IsRequired().HasColumnType("int").HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None);

            // Foreign keys
            HasRequired(a => a.Password).WithMany(b => b.PersonPasswords).HasForeignKey(c => c.PasswordId).WillCascadeOnDelete(false); // FK_PersonPassword_Password
            HasRequired(a => a.Person).WithMany(b => b.PersonPasswords).HasForeignKey(c => c.PersonId).WillCascadeOnDelete(false); // FK_PersonPassword_Person
        }
    }

}
// </auto-generated>
