// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.51
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace Pocos
{

    // PersonPhone
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.24.0.0")]
    public class PersonPhone
    {
        public int PersonId { get; set; } // PersonID (Primary key)
        public int PhoneNumberId { get; set; } // PhoneNumberID (Primary key)
        public int PhoneNumberTypeId { get; set; } // PhoneNumberTypeID (Primary key)

        // Foreign keys
        public virtual Person Person { get; set; } // FK_PersonPhone_Person
        public virtual PhoneNumber PhoneNumber { get; set; } // FK_PersonPhone_PhoneNumber
        public virtual PhoneNumberType PhoneNumberType { get; set; } // FK_PersonPhone_PhoneNumberType
    }

}
// </auto-generated>
