// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.51
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace Pocos
{

    // PersonAddress
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.24.0.0")]
    public class PersonAddress
    {
        public int PersonId { get; set; } // PersonID (Primary key)
        public int AddressId { get; set; } // AddressID (Primary key)
        public int AddressTypeId { get; set; } // AddressTypeID (Primary key)

        // Foreign keys
        public virtual Address Address { get; set; } // FK_PersonAddress_Address
        public virtual AddressType AddressType { get; set; } // FK_PersonAddress_AddressType
        public virtual Person Person { get; set; } // FK_PersonAddress_Person
    }

}
// </auto-generated>
