// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.51
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace Pocos
{

    // PolicyAmendment
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.24.0.0")]
    public class PolicyAmendment
    {
        public int Id { get; set; } // ID (Primary key)
        public int PolicyId { get; set; } // PolicyID
        public System.DateTime AmendmentDate { get; set; } // AmendmentDate
        public int AmendmentTypeId { get; set; } // AmendmentTypeID
        public decimal PreviousPremium { get; set; } // PreviousPremium
        public int AmmendedById { get; set; } // AmmendedByID

        // Reverse navigation
        public virtual System.Collections.Generic.ICollection<Question> Questions { get; set; } // Many to many mapping

        // Foreign keys
        public virtual Policy Policy { get; set; } // FK_PolicyAmendment_Policy
        public virtual PolicyAmentmentType PolicyAmentmentType { get; set; } // FK_PolicyAmendment_PolicyAmentmentType

        public PolicyAmendment()
        {
            Questions = new System.Collections.Generic.List<Question>();
        }
    }

}
// </auto-generated>
