// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.51
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace Pocos
{

    // PolicyDefinition
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.24.0.0")]
    public class PolicyDefinition
    {
        public int Id { get; set; } // ID (Primary key)
        public int PolicyTypeId { get; set; } // PolicyTypeID
        public string DefinitionName { get; set; } // DefinitionName (length: 30)
        public int? ProvidorOrUnderWriterId { get; set; } // ProvidorOrUnderWriterID

        // Reverse navigation
        public virtual System.Collections.Generic.ICollection<AddOn> AddOns { get; set; } // Many to many mapping
        public virtual System.Collections.Generic.ICollection<Policy> Policies { get; set; } // Policy.FK_Policy_PolicyDefinition
        public virtual System.Collections.Generic.ICollection<Question> Questions { get; set; } // Many to many mapping

        // Foreign keys
        public virtual PolicyType PolicyType { get; set; } // FK_PolicyDefinition_PolicyType
        public virtual Provider Provider { get; set; } // FK_PolicyDefinition_Provider

        public PolicyDefinition()
        {
            Policies = new System.Collections.Generic.List<Policy>();
            AddOns = new System.Collections.Generic.List<AddOn>();
            Questions = new System.Collections.Generic.List<Question>();
        }
    }

}
// </auto-generated>
