// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.51
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace Pocos
{

    // PolicyAmentmentType
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.24.0.0")]
    public class PolicyAmentmentType
    {
        public int Id { get; set; } // ID (Primary key)
        public string AmendmentType { get; set; } // AmendmentType (length: 20)

        // Reverse navigation
        public virtual System.Collections.Generic.ICollection<PolicyAmendment> PolicyAmendments { get; set; } // PolicyAmendment.FK_PolicyAmendment_PolicyAmentmentType

        public PolicyAmentmentType()
        {
            PolicyAmendments = new System.Collections.Generic.List<PolicyAmendment>();
        }
    }

}
// </auto-generated>
