// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.51
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace Pocos
{

    // Question
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.24.0.0")]
    public class Question
    {
        public int Id { get; set; } // ID (Primary key)
        public string QuestionText { get; set; } // QuestionText
        public int QuestionTypeId { get; set; } // QuestionTypeID

        ///<summary>
        /// 0 - No rating effect : 1 rating factor must be applied
        ///</summary>
        public string RatingEffect { get; set; } // RatingEffect (length: 10)
        public string QuestionHint { get; set; } // QuestionHint
        public int? GuiId { get; set; } // GuiID

        // Reverse navigation
        public virtual System.Collections.Generic.ICollection<Answer> Answers { get; set; } // Answer.FK_Answer_Question
        public virtual System.Collections.Generic.ICollection<PolicyAmendment> PolicyAmendments { get; set; } // Many to many mapping
        public virtual System.Collections.Generic.ICollection<PolicyDefinition> PolicyDefinitions { get; set; } // Many to many mapping
        public virtual System.Collections.Generic.ICollection<QuestionMultipleChoiceGroup> QuestionMultipleChoiceGroups { get; set; } // Many to many mapping
        public virtual System.Collections.Generic.ICollection<QuestionRange> QuestionRanges { get; set; } // Many to many mapping

        // Foreign keys
        public virtual QuestionType QuestionType { get; set; } // FK_Question_QuestionType

        public Question()
        {
            Answers = new System.Collections.Generic.List<Answer>();
            QuestionMultipleChoiceGroups = new System.Collections.Generic.List<QuestionMultipleChoiceGroup>();
            PolicyDefinitions = new System.Collections.Generic.List<PolicyDefinition>();
            PolicyAmendments = new System.Collections.Generic.List<PolicyAmendment>();
            QuestionRanges = new System.Collections.Generic.List<QuestionRange>();
        }
    }

}
// </auto-generated>
