// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.51
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace Pocos
{

    // QuestionRange
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.24.0.0")]
    public class QuestionRange
    {
        public int Id { get; set; } // ID (Primary key)
        public string RangeStart { get; set; } // RangeStart (length: 50)
        public string RangeEnd { get; set; } // RangeEnd (length: 50)

        // Reverse navigation
        public virtual System.Collections.Generic.ICollection<Answer> Answers { get; set; } // Many to many mapping
        public virtual System.Collections.Generic.ICollection<Question> Questions { get; set; } // Many to many mapping

        public QuestionRange()
        {
            Answers = new System.Collections.Generic.List<Answer>();
            Questions = new System.Collections.Generic.List<Question>();
        }
    }

}
// </auto-generated>
