// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.51
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace Pocos
{

    // RatingFactor
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.24.0.0")]
    public class RatingFactorConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<RatingFactor>
    {
        public RatingFactorConfiguration()
            : this("dbo")
        {
        }

        public RatingFactorConfiguration(string schema)
        {
            ToTable("RatingFactor", schema);
            HasKey(x => x.Id);

            Property(x => x.Id).HasColumnName(@"ID").IsRequired().HasColumnType("int").HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None);
            Property(x => x.RatingOperator).HasColumnName(@"RatingOperator").IsOptional().HasColumnType("int");
            Property(x => x.RatingOperand).HasColumnName(@"RatingOperand").IsOptional().HasColumnType("decimal").HasPrecision(4,4);
            Property(x => x.RatingbaseRateId).HasColumnName(@"RatingbaseRateID").IsRequired().HasColumnType("int");

            // Foreign keys
            HasRequired(a => a.RatingBaseRate).WithMany(b => b.RatingFactors).HasForeignKey(c => c.RatingbaseRateId).WillCascadeOnDelete(false); // FK_RatingFactor_RatingBaseRate
        }
    }

}
// </auto-generated>
