// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.51
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace Pocos
{

    // RatingFactorOnPolicy
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.24.0.0")]
    public class RatingFactorOnPolicyConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<RatingFactorOnPolicy>
    {
        public RatingFactorOnPolicyConfiguration()
            : this("dbo")
        {
        }

        public RatingFactorOnPolicyConfiguration(string schema)
        {
            ToTable("RatingFactorOnPolicy", schema);
            HasKey(x => new { x.AnswerId, x.PolicyId, x.RatingFactorId });

            Property(x => x.RatingFactorId).HasColumnName(@"RatingFactorID").IsRequired().HasColumnType("int").HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None);
            Property(x => x.PolicyId).HasColumnName(@"PolicyID").IsRequired().HasColumnType("int").HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None);
            Property(x => x.AnswerId).HasColumnName(@"AnswerID").IsRequired().HasColumnType("int").HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None);

            // Foreign keys
            HasRequired(a => a.Answer).WithMany(b => b.RatingFactorOnPolicies).HasForeignKey(c => c.AnswerId).WillCascadeOnDelete(false); // FK_RatingFactorOnPolicy_Answer
            HasRequired(a => a.Policy).WithMany(b => b.RatingFactorOnPolicies).HasForeignKey(c => c.PolicyId).WillCascadeOnDelete(false); // FK_RatingFactorOnPolicy_Policy
            HasRequired(a => a.RatingFactor).WithMany(b => b.RatingFactorOnPolicies).HasForeignKey(c => c.RatingFactorId).WillCascadeOnDelete(false); // FK_RatingFactorOnPolicy_RatingFactor
        }
    }

}
// </auto-generated>
