// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.51
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace Pocos
{

    // RatingBaseRate
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.24.0.0")]
    public class RatingBaseRateConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<RatingBaseRate>
    {
        public RatingBaseRateConfiguration()
            : this("dbo")
        {
        }

        public RatingBaseRateConfiguration(string schema)
        {
            ToTable("RatingBaseRate", schema);
            HasKey(x => x.Id);

            Property(x => x.Id).HasColumnName(@"ID").IsRequired().HasColumnType("int").HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None);
            Property(x => x.ProviderId).HasColumnName(@"ProviderID").IsRequired().HasColumnType("int");
            Property(x => x.ValidFrom).HasColumnName(@"ValidFrom").IsRequired().HasColumnType("datetime");
            Property(x => x.ValidTo).HasColumnName(@"ValidTo").IsOptional().HasColumnType("datetime");
            Property(x => x.BaseRate).HasColumnName(@"BaseRate").IsRequired().HasColumnType("decimal").HasPrecision(4,2);
        }
    }

}
// </auto-generated>
