// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.51
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace Pocos
{

    // Salutation
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.24.0.0")]
    public class Salutation
    {
        public int Id { get; set; } // ID (Primary key)
        public string Title { get; set; } // Title (length: 30)

        // Reverse navigation
        public virtual System.Collections.Generic.ICollection<Person> People { get; set; } // Person.FK_Person_Salutatiion

        public Salutation()
        {
            People = new System.Collections.Generic.List<Person>();
        }
    }

}
// </auto-generated>
