// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.51
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace Pocos
{

    // Town
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.24.0.0")]
    public class Town
    {
        public int Id { get; set; } // ID (Primary key)
        public string TownName { get; set; } // TownName (length: 20)

        // Reverse navigation
        public virtual System.Collections.Generic.ICollection<Address> Addresses { get; set; } // Address.FK_Address_City
        public virtual System.Collections.Generic.ICollection<Country> Countries { get; set; } // Many to many mapping

        public Town()
        {
            Addresses = new System.Collections.Generic.List<Address>();
            Countries = new System.Collections.Generic.List<Country>();
        }
    }

}
// </auto-generated>
