// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.51
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace OsipDal.EF
{

    // PersonLogin
    [System.CodeDom.Compiler.GeneratedCodeAttribute("EF.Reverse.POCO.Generator", "2.19.1.0")]
    public class PersonLogin
    {
        public int PersonId { get; set; } // PersonID (Primary key)
        public int LoginId { get; set; } // LoginID (Primary key)
        public int TargetSystemId { get; set; } // targetSystemID (Primary key)

        // Foreign keys
        public virtual Login Login { get; set; } // FK_PersonLogin_Login
        public virtual Person Person { get; set; } // FK_PersonLogin_Person
        public virtual TargetSystem TargetSystem { get; set; } // FK_PersonLogin_TargetSystem
    }

}
// </auto-generated>
